// <auto-generated />
using System;
using EscalaApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EscalaApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408182415_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Escala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Escalas");
                });

            modelBuilder.Entity("EscalaApi.Domain.Entities.GrupoEscala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FuncaoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FuncaoId");

                    b.ToTable("GruposEscala");
                });

            modelBuilder.Entity("EscalaApi.Domain.Entities.Participante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("EscalaId")
                        .HasColumnType("int");

                    b.Property<int?>("GrupoEscalaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EscalaId");

                    b.HasIndex("GrupoEscalaId");

                    b.ToTable("Participantes");
                });

            modelBuilder.Entity("EscalaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("EscalaId")
                        .HasColumnType("int");

                    b.Property<int>("FuncaoId")
                        .HasColumnType("int");

                    b.Property<int>("ParticipanteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EscalaId");

                    b.HasIndex("FuncaoId");

                    b.HasIndex("ParticipanteId");

                    b.ToTable("EscalaItems");
                });

            modelBuilder.Entity("Funcao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EscalaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantidadePessoas")
                        .HasColumnType("int");

                    b.Property<int>("tipoExecucao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EscalaId");

                    b.ToTable("Funcoes");
                });

            modelBuilder.Entity("ParticipanteFuncao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FuncaoId")
                        .HasColumnType("int");

                    b.Property<int>("ParticipanteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FuncaoId");

                    b.HasIndex("ParticipanteId");

                    b.ToTable("ParticipanteFuncaos");
                });

            modelBuilder.Entity("ParticipanteGrupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GrupoEscalaId")
                        .HasColumnType("int");

                    b.Property<int>("ParticipanteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupoEscalaId");

                    b.HasIndex("ParticipanteId");

                    b.ToTable("ParticipanteGrupos");
                });

            modelBuilder.Entity("EscalaApi.Domain.Entities.GrupoEscala", b =>
                {
                    b.HasOne("Funcao", "Funcao")
                        .WithMany("Grupos")
                        .HasForeignKey("FuncaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcao");
                });

            modelBuilder.Entity("EscalaApi.Domain.Entities.Participante", b =>
                {
                    b.HasOne("Escala", null)
                        .WithMany("Participantes")
                        .HasForeignKey("EscalaId");

                    b.HasOne("EscalaApi.Domain.Entities.GrupoEscala", null)
                        .WithMany("Participantes")
                        .HasForeignKey("GrupoEscalaId");
                });

            modelBuilder.Entity("EscalaItem", b =>
                {
                    b.HasOne("Escala", "Escala")
                        .WithMany()
                        .HasForeignKey("EscalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Funcao", "Funcao")
                        .WithMany()
                        .HasForeignKey("FuncaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscalaApi.Domain.Entities.Participante", "Participante")
                        .WithMany()
                        .HasForeignKey("ParticipanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Escala");

                    b.Navigation("Funcao");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("Funcao", b =>
                {
                    b.HasOne("Escala", null)
                        .WithMany("Funcoes")
                        .HasForeignKey("EscalaId");
                });

            modelBuilder.Entity("ParticipanteFuncao", b =>
                {
                    b.HasOne("Funcao", "Funcao")
                        .WithMany("ParticipanteFuncoes")
                        .HasForeignKey("FuncaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscalaApi.Domain.Entities.Participante", "Participante")
                        .WithMany()
                        .HasForeignKey("ParticipanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcao");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("ParticipanteGrupo", b =>
                {
                    b.HasOne("EscalaApi.Domain.Entities.GrupoEscala", "GrupoEscala")
                        .WithMany()
                        .HasForeignKey("GrupoEscalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EscalaApi.Domain.Entities.Participante", "Participante")
                        .WithMany()
                        .HasForeignKey("ParticipanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoEscala");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("Escala", b =>
                {
                    b.Navigation("Funcoes");

                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("EscalaApi.Domain.Entities.GrupoEscala", b =>
                {
                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("Funcao", b =>
                {
                    b.Navigation("Grupos");

                    b.Navigation("ParticipanteFuncoes");
                });
#pragma warning restore 612, 618
        }
    }
}
